version: "3.7"
services:
  clarity_web:
    container_name: clarity_web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - DB_URL=$DB_URL
    ports:
      - "8002:8002"
    volumes:
      - ./static/:/app/clarity_minds/static/
      - ./media/:/app/clarity_minds/media/
