# Generated by Django 4.2.5 on 2023-10-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="emoji",
            field=models.CharField(
                choices=[
                    ("😃", "😃 - Feliz"),
                    ("😊", "😊 - Legal"),
                    ("😐", "😐 - Normal/Neutro"),
                    ("😥", "😥 - Preocupado"),
                    ("😞", "😞 - Chateado"),
                    ("😫", "😫 - Triste"),
                    ("😵", "😵 - Cansado"),
                    ("😡", "😡 - Raiva"),
                ],
                max_length=255,
                verbose_name="Emoji",
            ),
        ),
    ]
